/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import controller.DecidirSobreArtigosController;
import eventoscientificos.Distribuicao;
import eventoscientificos.Empresa;
import eventoscientificos.Evento;
import eventoscientificos.Decisao;
import eventoscientificos.MecanismoDecisao;
import eventoscientificos.Revisor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pereira
 */
public class DecidirSobreArtigoUI extends javax.swing.JDialog {

    private static Empresa empresa;
    private DecidirSobreArtigosController decidirSobreArtigoController;
    private List<Evento> listaEventos;
    private int iEvento = -1;
    private List<MecanismoDecisao> listaMecanimosDecisao;
    private int iMecanismo = -1;
    private List<Decisao> listaDecisoes;
    /**
     * Creates new form DecidirSobreArtigoUI
     */
    public DecidirSobreArtigoUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, modal);
        initComponents();
        this.empresa=empresa;
        decidirSobreArtigoController= new DecidirSobreArtigosController(this.empresa);
        jPanelEvento.setVisible(true);
        jPanelMecanismo.setVisible(false);
    }

    /**
     * arranca janela
     */
    public void run() {
        String organizador = JOptionPane.showInputDialog(this,
                "Insira o ID de organizador", "Login", JOptionPane.INFORMATION_MESSAGE);
        if (organizador != null) {

            listaEventos = decidirSobreArtigoController.ListarEventosOrganizador(organizador);

            if (listaEventos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Utilizador não associado a nenhum evento", "Distribuir Revisões",
                        JOptionPane.ERROR_MESSAGE);
                dispose();
            } else {
                for (Evento evento : listaEventos) {
                    jcbEvento.addItem(evento.getM_strTitulo());
                }
                pack();
                setResizable(false);
                setVisible(true);
            }
        } else {
            JOptionPane.showInputDialog(this,
                    "O ID introduzido não é válido", "Login", JOptionPane.ERROR_MESSAGE);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEvento = new javax.swing.JPanel();
        lblEvento = new javax.swing.JLabel();
        jcbEvento = new javax.swing.JComboBox();
        btnOKEvento = new javax.swing.JButton();
        btnCancelEvento = new javax.swing.JButton();
        jPanelMecanismo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcMecanismos = new javax.swing.JComboBox();
        btnOKMecanismo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Decidir sobre artigo");

        lblEvento.setText("Selecione Evento:");

        btnOKEvento.setText("OK");
        btnOKEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKEventoActionPerformed(evt);
            }
        });

        btnCancelEvento.setText("Cancelar");

        javax.swing.GroupLayout jPanelEventoLayout = new javax.swing.GroupLayout(jPanelEvento);
        jPanelEvento.setLayout(jPanelEventoLayout);
        jPanelEventoLayout.setHorizontalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelEventoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnOKEvento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEventoLayout.createSequentialGroup()
                        .addComponent(jcbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEventoLayout.createSequentialGroup()
                        .addComponent(btnCancelEvento)
                        .addGap(58, 58, 58))))
        );
        jPanelEventoLayout.setVerticalGroup(
            jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEventoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvento)
                    .addComponent(jcbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOKEvento)
                    .addComponent(btnCancelEvento))
                .addContainerGap())
        );

        jLabel1.setText("Selecione Mecanismo:");

        btnOKMecanismo.setText("OK");
        btnOKMecanismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKMecanismoActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout jPanelMecanismoLayout = new javax.swing.GroupLayout(jPanelMecanismo);
        jPanelMecanismo.setLayout(jPanelMecanismoLayout);
        jPanelMecanismoLayout.setHorizontalGroup(
            jPanelMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMecanismoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcMecanismos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanelMecanismoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnOKMecanismo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(53, 53, 53))
        );
        jPanelMecanismoLayout.setVerticalGroup(
            jPanelMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMecanismoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcMecanismos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOKMecanismo)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelMecanismo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKEventoActionPerformed
        iEvento = jcbEvento.getSelectedIndex();
        if (iEvento != -1) {
            Evento e = new Evento();
            decidirSobreArtigoController.setM_evento(e);
            listaMecanimosDecisao = decidirSobreArtigoController.getListaMecanismosDecisao();

            if (listaMecanimosDecisao.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não existe mecanismo de decisao", "Decisão Artigo",
                        JOptionPane.ERROR_MESSAGE);
                dispose();
            } else {
                for (MecanismoDecisao MecanismoDecisao : listaMecanimosDecisao) {
                    jcMecanismos.addItem(MecanismoDecisao.getNome());
                }
               
                jPanelMecanismo.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tem que seleccionar um evento primeiro", "Decisão", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOKEventoActionPerformed

    private void btnOKMecanismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKMecanismoActionPerformed
        iMecanismo = jcMecanismos.getSelectedIndex();
        listaDecisoes = new ArrayList<>();
        String decisao = "";
        if (iMecanismo != -1) {
            decidirSobreArtigoController.setMecanismoDecisao(iMecanismo);
            JOptionPane.showMessageDialog(this, "Decisão definida com Sucesso", "Decisão", JOptionPane.OK_OPTION);
            listaDecisoes = decidirSobreArtigoController.getListaDecisoes();
            if (listaDecisoes != null) {
                for (int i = 0; i < listaDecisoes.size(); i++) {
                    decisao = decisao + decidirSobreArtigoController.getProcessoDecisao().getM_decisao()+ "/n"+
                            decidirSobreArtigoController.getProcessoDecisao().getM_listaDistribuicao().toString();
                    }
                    decisao = decisao + "\n";
                }
                JOptionPane.showMessageDialog(this, decisao, "Decisao!", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(this, "Nao existem dados suficientes para efectuar a decisao!", "Erro!", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
        
    
    }//GEN-LAST:event_btnOKMecanismoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecidirSobreArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecidirSobreArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecidirSobreArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecidirSobreArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DecidirSobreArtigoUI dialog = new DecidirSobreArtigoUI(new javax.swing.JFrame(), true, empresa);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelEvento;
    private javax.swing.JButton btnOKEvento;
    private javax.swing.JButton btnOKMecanismo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelEvento;
    private javax.swing.JPanel jPanelMecanismo;
    private javax.swing.JComboBox jcMecanismos;
    private javax.swing.JComboBox jcbEvento;
    private javax.swing.JLabel lblEvento;
    // End of variables declaration//GEN-END:variables
}
