/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.DistribuirRevisoesController;
import eventoscientificos.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author Lopes
 */
public class DistribuirRevisoesUI extends javax.swing.JDialog {

    private static Empresa empresa;
    private DistribuirRevisoesController distribuirRevisoesController;
    private List<Evento> listaEventos;
    private int iEvento = -1;
    private List<MecanismoDistribuicao> listaMecanimos;
    private int iMecanismo = -1;
    private List<Distribuicao> listaDistribuicoes;

    public DistribuirRevisoesUI(Empresa empresa) {
        this.empresa = empresa;

    }

    /**
     * Creates new form SubmissaoArtigoUI
     */
    public DistribuirRevisoesUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, modal);
        initComponents();
        this.empresa = empresa;
        distribuirRevisoesController = new DistribuirRevisoesController(empresa);
        jPanelEscolhaMecanismo.setVisible(false);
    }

    /**
     * arranca janela
     */
    public void run() {
        String organizador = JOptionPane.showInputDialog(this,
                "Insira o ID de organizador", "Login", JOptionPane.INFORMATION_MESSAGE);
        if (organizador != null) {

            listaEventos = distribuirRevisoesController.novaDistribuicaoOrganizador(organizador);

            if (listaEventos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Utilizador não associado a nenhum evento", "Distribuir Revisões",
                        JOptionPane.ERROR_MESSAGE);
                dispose();
            } else {
                for (Evento evento : listaEventos) {
                    cmbEvento.addItem(evento.getM_strTitulo());
                }
                pack();
                setResizable(false);
                setVisible(true);
            }
        } else {
            JOptionPane.showInputDialog(this,
                    "O ID introduzido não é válido", "Login", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEscolhaMecanismo = new javax.swing.JPanel();
        cmbMecanismo = new javax.swing.JComboBox();
        jButtonCancelarMec = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonOkMecanismo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelEscolhaEvento = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        cmbEvento = new javax.swing.JComboBox();
        jButtonOkEvento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distribuir Revisões");

        jButtonCancelarMec.setText("Cancelar");
        jButtonCancelarMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarMecActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jButtonOkMecanismo.setText("Ok");
        jButtonOkMecanismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkMecanismoActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleciona Mecanismo:");

        javax.swing.GroupLayout jPanelEscolhaMecanismoLayout = new javax.swing.GroupLayout(jPanelEscolhaMecanismo);
        jPanelEscolhaMecanismo.setLayout(jPanelEscolhaMecanismoLayout);
        jPanelEscolhaMecanismoLayout.setHorizontalGroup(
            jPanelEscolhaMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscolhaMecanismoLayout.createSequentialGroup()
                .addGroup(jPanelEscolhaMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEscolhaMecanismoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButtonOkMecanismo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarMec))
                    .addGroup(jPanelEscolhaMecanismoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(cmbMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );
        jPanelEscolhaMecanismoLayout.setVerticalGroup(
            jPanelEscolhaMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscolhaMecanismoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelEscolhaMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelEscolhaMecanismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarMec)
                    .addComponent(jButtonOkMecanismo))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonOkEvento.setText("Ok");
        jButtonOkEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkEventoActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleciona Evento:");

        javax.swing.GroupLayout jPanelEscolhaEventoLayout = new javax.swing.GroupLayout(jPanelEscolhaEvento);
        jPanelEscolhaEvento.setLayout(jPanelEscolhaEventoLayout);
        jPanelEscolhaEventoLayout.setHorizontalGroup(
            jPanelEscolhaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscolhaEventoLayout.createSequentialGroup()
                .addGroup(jPanelEscolhaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEscolhaEventoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButtonOkEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addGroup(jPanelEscolhaEventoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );
        jPanelEscolhaEventoLayout.setVerticalGroup(
            jPanelEscolhaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscolhaEventoLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanelEscolhaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelEscolhaEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonOkEvento))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEscolhaMecanismo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelEscolhaEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEscolhaMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanelEscolhaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkEventoActionPerformed
        iEvento = cmbEvento.getSelectedIndex();
        if (iEvento != -1) {
            Evento e = new Evento();
            distribuirRevisoesController.setEvento(e);
            listaMecanimos = distribuirRevisoesController.getMecanismoDistribuicao();

            if (listaMecanimos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Não existe mecanismo de distribuição", "Distribuir Revisões",
                        JOptionPane.ERROR_MESSAGE);
                dispose();
            } else {
                for (MecanismoDistribuicao Mecanismo : listaMecanimos) {
                    cmbMecanismo.addItem(Mecanismo.getNome());
                }
                jPanelEscolhaEvento.setVisible(false);
                jPanelEscolhaMecanismo.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tem que seleccionar um evento primeiro", "Distribuir Revisões", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOkEventoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCancelarMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarMecActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarMecActionPerformed

    private void jButtonOkMecanismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkMecanismoActionPerformed
        iMecanismo = cmbMecanismo.getSelectedIndex();
        listaDistribuicoes = new ArrayList<>();
        String revisoes = "";
        if (iMecanismo != -1) {
            distribuirRevisoesController.setMecanismoDistribuicao(iMecanismo);
            JOptionPane.showMessageDialog(this, "Revisões distribuidos com Sucesso", "Distribuir Revisões", JOptionPane.OK_OPTION);
            listaDistribuicoes = distribuirRevisoesController.getListaDistribuicoes();
            if (listaDistribuicoes != null) {
                for (Distribuicao distribuicao : listaDistribuicoes) {
                    revisoes = revisoes + distribuicao.getM_artigo().toString();
                    for (Revisor revisor : distribuicao.getM_listaRevisores()) {
                        revisoes = revisoes + ": " + revisor.getM_strNome() + ", ";
                    }
                    revisoes = revisoes + "\n";
                }
                JOptionPane.showMessageDialog(this, revisoes, "Distribuir Revisões!", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(this, "Nao existem dados suficientes para efectuar a distribuicao!", "Erro!", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tem que seleccionar um mecanismo primeiro!", "Distribuir Revisões", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOkMecanismoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistribuirRevisoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistribuirRevisoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistribuirRevisoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistribuirRevisoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DistribuirRevisoesUI dialog = new DistribuirRevisoesUI(new javax.swing.JFrame(), true, empresa);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEvento;
    private javax.swing.JComboBox cmbMecanismo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelarMec;
    private javax.swing.JButton jButtonOkEvento;
    private javax.swing.JButton jButtonOkMecanismo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelEscolhaEvento;
    private javax.swing.JPanel jPanelEscolhaMecanismo;
    // End of variables declaration//GEN-END:variables
}
