/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import controller.RegistarUtilizadorController;
import eventoscientificos.Empresa;
import eventoscientificos.RegistoUtilizador;
import javax.swing.JOptionPane;


/**
 *
 * @author Pereira
 */
public class RegistarUtilizadorUI extends javax.swing.JDialog {

    
    private static Empresa m_empresa;
    private RegistarUtilizadorController m_registoUtilizadorController;
    private RegistoUtilizador m_registoUtilizador;
    
    /**
     * Creates new form RegistarUtilizadorUI
     */
    public RegistarUtilizadorUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, modal);
        initComponents();
        this.m_empresa=empresa;
        this.m_registoUtilizadorController= new RegistarUtilizadorController(empresa);
        
    }
    public void run()
    {
    pack();
    setResizable(false);
    setVisible(true);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JTextField();
        jTextUserName = new javax.swing.JTextField();
        jLPassword = new javax.swing.JLabel();
        jLUserName = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jTexEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar Utilizador");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLNome.setText("Nome:");

        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });

        jLPassword.setText("Password:");

        jLUserName.setText("Username:");

        jLEmail.setText("E-mail:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLPassword)
                            .addComponent(jLNome))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jTextNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLUserName)
                            .addComponent(jLEmail))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextUserName)
                            .addComponent(jTexEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPassword)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTexEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCancel))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(!jTextNome.getText().isEmpty()&& !jTextPassword.getText().isEmpty() && 
             !jTextUserName.getText().isEmpty() && !jTexEmail.getText().isEmpty())
     {   
        m_registoUtilizadorController.setDados(jTextNome.getText(), jTextPassword.getText(), 
             jTextUserName.getText(), jTexEmail.getText());
         if(m_registoUtilizadorController.getM_utilizador().validaEmail())
         {
//                     JOptionPane.showConfirmDialog(RegistarUtilizadorUI.this, m_registoUtilizadorController.getM_utilizador(),
//                                    "Adicionar utilizador?",JOptionPane.OK_CANCEL_OPTION);
                    if(JOptionPane.showConfirmDialog(RegistarUtilizadorUI.this, m_registoUtilizadorController.getM_utilizador(),
                                    "Adicionar utilizador?",JOptionPane.OK_CANCEL_OPTION)==0)
                    
                                        if(m_registoUtilizadorController.ValidarUtilizador(m_registoUtilizadorController.setDados
                                            (jTextNome.getText(), jTextPassword.getText(), jTextUserName.getText(), jTexEmail.getText())))
                                        {
                                            JOptionPane.showMessageDialog(RegistarUtilizadorUI.this, "Utilizador Adicionado\n"+m_registoUtilizadorController.getM_utilizador() 
                                                                                  , "Registar Utilizador", JOptionPane.INFORMATION_MESSAGE);
                                        this.jTextNome.setText(""); this.jTextPassword.setText(""); this.jTextUserName.setText(""); this.jTexEmail.setText("");
                                        }
                    
                    else
                       {                     
                       JOptionPane.showMessageDialog(RegistarUtilizadorUI.this,"Este utilizador já existe no sistema\n" + m_registoUtilizadorController.getM_utilizador(), "Registar Utilizador", JOptionPane.ERROR_MESSAGE);
                       this.jTextNome.setText(""); this.jTextPassword.setText(""); this.jTextUserName.setText(""); this.jTexEmail.setText("");}
          }
         else 
            JOptionPane.showMessageDialog(RegistarUtilizadorUI.this,m_registoUtilizadorController.getM_utilizador().getM_strEmail(),"E-mail incorreto",JOptionPane.ERROR_MESSAGE);    
     }
     else   JOptionPane.showMessageDialog(RegistarUtilizadorUI.this,"Campos vazios\n" , "Registar Utilizador", JOptionPane.ERROR_MESSAGE);
                                    
         
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RegistarUtilizadorUI dialog = new RegistarUtilizadorUI(new javax.swing.JFrame() ,
                        true,m_empresa);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
               
                dialog.setVisible(true);
            }
          
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLPassword;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JTextField jTexEmail;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextUserName;
    // End of variables declaration//GEN-END:variables
}
