/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.SubmeterArtigoController;
import eventoscientificos.Autor;
import eventoscientificos.Empresa;
import eventoscientificos.Utilizador;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class SubmeterArtigoUI extends javax.swing.JDialog {

    private static final int JANELA_POSICAO_X = 200, JANELA_POSICAO_Y = 200;

    private static Empresa empresa;
    private SubmeterArtigoController submeterArtigoController;
    private int iEvento = -1;

    private Utilizador utilizadorID;

    public SubmeterArtigoUI(Empresa empresa) {
        this.empresa = empresa;
    }

    /**
     * Creates new form SubmissaoArtigoUI
     */
    public SubmeterArtigoUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, "Submeter artigo", modal);
        this.empresa = empresa;
        this.submeterArtigoController = new SubmeterArtigoController(empresa);
        initComponents();
        if (submeterArtigoController.getListaEventosPodeSub().length > 0) {
            for (String eventoNome : submeterArtigoController.getListaEventosPodeSub()) {
                cmbEvento.addItem(eventoNome);
            }
        }
        jPanel2.setVisible(false);

    }

    public void run() {
        String utilizador = JOptionPane.showInputDialog(this,
                "Insira o utilizador", "Login", JOptionPane.INFORMATION_MESSAGE);
        if (utilizador != null) {

            utilizadorID = empresa.getM_registaUtilizador().getUtilizador(utilizador);

            if (utilizadorID == null) {
                JOptionPane.showMessageDialog(this, "Utilizador inexistente!", "Submeter artigo",
                        JOptionPane.ERROR_MESSAGE);
                dispose();
            } else {
                
                pack();
                setResizable(false);
                setLocation(JANELA_POSICAO_X, JANELA_POSICAO_Y);
                setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResumo = new javax.swing.JTextArea();
        btnSubmeter = new javax.swing.JButton();
        lblTitulo1 = new javax.swing.JLabel();
        cmbEvento = new javax.swing.JComboBox();
        lblEvento = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        lblTipo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAutorCorrespondente = new javax.swing.JLabel();
        cmbAutorCorr = new javax.swing.JComboBox();
        btnSeleccionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Submeter artigo");
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(600, 300));

        jPan1.setMaximumSize(new java.awt.Dimension(500, 200));
        jPan1.setPreferredSize(new java.awt.Dimension(100, 50));

        txtResumo.setColumns(20);
        txtResumo.setLineWrap(true);
        txtResumo.setRows(5);
        jScrollPane1.setViewportView(txtResumo);

        btnSubmeter.setText("Iniciar submissão");
        btnSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmeterActionPerformed(evt);
            }
        });

        lblTitulo1.setText("Resumo:");

        cmbEvento.setToolTipText("");

        lblEvento.setText("Evento:");

        lblTitulo.setText("Titulo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Full Paper", "Short Paper", "Post Paper" }));

        lblTipo.setText("Tipo artigo");

        javax.swing.GroupLayout jPan1Layout = new javax.swing.GroupLayout(jPan1);
        jPan1.setLayout(jPan1Layout);
        jPan1Layout.setHorizontalGroup(
            jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPan1Layout.createSequentialGroup()
                            .addComponent(lblTitulo)
                            .addGap(41, 41, 41))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan1Layout.createSequentialGroup()
                            .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPan1Layout.createSequentialGroup()
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo1)
                            .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPan1Layout.createSequentialGroup()
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmeter))
                    .addComponent(cmbEvento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPan1Layout.setVerticalGroup(
            jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmeter)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblAutorCorrespondente.setText("Autor correspondente");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAutorCorrespondente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbAutorCorr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblAutorCorrespondente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAutorCorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionar)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(113, 23));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPan1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPan1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmeterActionPerformed
        // TODO add your handling code here:
        iEvento = cmbEvento.getSelectedIndex();
        if (iEvento != -1) {
            //Adiciona os dados da submissão
            if (!(txtTitulo.getText().isEmpty() || txtResumo.getText().isEmpty())) {

                submeterArtigoController.iniciarSubmissao();
                submeterArtigoController.selectEvento(empresa.getM_registoEventos().
                        getEvento((String) cmbEvento.getSelectedItem()));

                submeterArtigoController.setDados(txtTitulo.getText(), txtResumo.getText());

                while (JOptionPane.showConfirmDialog(this, "Adicionar autor?",
                        "Adicionar autores",
                        JOptionPane.YES_NO_OPTION) == 0) {

                    String nomeAutor = JOptionPane.showInputDialog(this, "Nome do autor:",
                            "Inserir autores", JOptionPane.OK_CANCEL_OPTION);
                    Utilizador utilizador = submeterArtigoController.obterAutor(nomeAutor);
                    String afiliacao = "";
                    if (utilizador != null) {
                        afiliacao = JOptionPane.showInputDialog(this, "Afiliação:",
                                "Inserir afiliação", JOptionPane.OK_CANCEL_OPTION);

                        submeterArtigoController.addAutor(submeterArtigoController.
                                novoAutor(utilizador.getM_strNome(), afiliacao,
                                        utilizador.getM_strEmail()));
                        submeterArtigoController.setTipoArtigo((String) cmbTipo.
                                getSelectedItem());

                    } else {
                        JOptionPane.showMessageDialog(this, "O autor introduzido não faz parte da lista de utilizadores!",
                                "Submeter artigo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
                jPan1.setVisible(false);
                jPanel2.setVisible(true);
                for (Autor autorCorrespondente : submeterArtigoController.getPossiveisAutoresCorrespondentes()) {
                    cmbAutorCorr.addItem(autorCorrespondente.getM_strNome());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tem que inserir um titulo e resumo do artigo!",
                        "Dados inválidos!", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Tem que seleccionar um evento primeiro");
        }
    }//GEN-LAST:event_btnSubmeterActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        if (cmbAutorCorr.getSelectedIndex() != -1) {
            Autor autorCorrespondente = new Autor();
            autorCorrespondente.setM_Utilizador(submeterArtigoController.
                    obterAutor((String) cmbAutorCorr.getSelectedItem()));

            submeterArtigoController.setCorrespondente(autorCorrespondente);
            String nomeFicheiro = JOptionPane.showInputDialog(this, "Insira o ficheiro:",
                    "Submeter artigo", JOptionPane.INFORMATION_MESSAGE);
            submeterArtigoController.setFicheiro(nomeFicheiro);

            //Adiciona tópicos
            while (JOptionPane.showConfirmDialog(this, "Adicionar um tópico?", "Submeter artigo",
                    JOptionPane.YES_NO_OPTION) == 0) {
                String tp = JOptionPane.showInputDialog(this, "Insira o tópico:",
                        "Submeter artigo", JOptionPane.INFORMATION_MESSAGE);

                if (submeterArtigoController.
                        topicoExisteEvento(tp) == null) {
                    JOptionPane.showMessageDialog(this, "Tópico não existe no evento!");
                } else {
                    submeterArtigoController.addTopico(submeterArtigoController.
                            topicoExisteEvento(tp));
                }
            }

        }

        if (submeterArtigoController.getTopicosArtigo() != null) {
            submeterArtigoController.setListaTopicosArtigo(
                    submeterArtigoController.getTopicosArtigo());
        }

        boolean sucesso = submeterArtigoController.registarSubmissao();
        if(!sucesso){
            JOptionPane.showMessageDialog(this,
                "Artigo não submetido!",
                "Submeter artigo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "Artigo submetido com sucesso!",
                "Submeter artigo", JOptionPane.INFORMATION_MESSAGE);
        }

        dispose();

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubmeterArtigoUI dialog = new SubmeterArtigoUI(new javax.swing.JFrame(), true, empresa);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnSubmeter;
    private javax.swing.JComboBox cmbAutorCorr;
    private javax.swing.JComboBox cmbEvento;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JPanel jPan1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutorCorrespondente;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextArea txtResumo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
