/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.SubmeterArtigoController;
import eventoscientificos.Autor;
import eventoscientificos.Empresa;
import eventoscientificos.Evento;
import eventoscientificos.Utilizador;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class SubmeterArtigoUI extends javax.swing.JDialog {

    private static Empresa empresa;
    private SubmeterArtigoController submeterArtigoController;
    private int iEvento = -1;

    private Utilizador utilizadorID;

    public SubmeterArtigoUI(Empresa empresa) {
        this.empresa = empresa;

    }

    /**
     * Creates new form SubmissaoArtigoUI
     */
    public SubmeterArtigoUI(java.awt.Frame parent, boolean modal, Empresa empresa) {
        super(parent, "Submeter artigo", modal);
        this.empresa = empresa;
        this.submeterArtigoController = new SubmeterArtigoController(empresa);
        initComponents();
        if (submeterArtigoController.getListaEventosPodeSub().length > 0) {
            for (String eventoNome : submeterArtigoController.getListaEventosPodeSub()) {
                cmbEvento.addItem(eventoNome);
            }
        }
        jPanel2.setVisible(false);

    }

    public void run() {
        String utilizador = JOptionPane.showInputDialog(this,
                "Insira o utilizador", "Login", JOptionPane.INFORMATION_MESSAGE);
        if (utilizador != null) {

            utilizadorID = empresa.getM_registaUtilizador().getUtilizador(utilizador);

            if (utilizadorID == null) {
                JOptionPane.showMessageDialog(this, "Utilizador inexistente!", "Submeter artigo",
                        JOptionPane.ERROR_MESSAGE);
                dispose();
            } else {

                pack();
                setResizable(false);
                setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResumo = new javax.swing.JTextArea();
        btnSubmeter = new javax.swing.JButton();
        lblTitulo1 = new javax.swing.JLabel();
        cmbEvento = new javax.swing.JComboBox();
        lblEvento = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAutorCorrespondente = new javax.swing.JLabel();
        cmbAutorCorr = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Submeter artigo");
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(600, 300));

        jPan1.setMaximumSize(new java.awt.Dimension(500, 200));
        jPan1.setPreferredSize(new java.awt.Dimension(100, 50));

        txtResumo.setColumns(20);
        txtResumo.setLineWrap(true);
        txtResumo.setRows(5);
        jScrollPane1.setViewportView(txtResumo);

        btnSubmeter.setText("Submeter artigo");
        btnSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmeterActionPerformed(evt);
            }
        });

        lblTitulo1.setText("Resumo:");

        cmbEvento.setToolTipText("");

        lblEvento.setText("Evento:");

        lblTitulo.setText("Titulo:");

        javax.swing.GroupLayout jPan1Layout = new javax.swing.GroupLayout(jPan1);
        jPan1.setLayout(jPan1Layout);
        jPan1Layout.setHorizontalGroup(
            jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubmeter)
                    .addGroup(jPan1Layout.createSequentialGroup()
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPan1Layout.createSequentialGroup()
                                    .addComponent(lblTitulo)
                                    .addGap(41, 41, 41))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan1Layout.createSequentialGroup()
                                    .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPan1Layout.createSequentialGroup()
                                .addComponent(lblTitulo1)
                                .addGap(29, 29, 29)))
                        .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTitulo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPan1Layout.setVerticalGroup(
            jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmeter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAutorCorrespondente.setText("Autor correspondente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblAutorCorrespondente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbAutorCorr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblAutorCorrespondente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAutorCorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPan1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPan1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmeterActionPerformed
        // TODO add your handling code here:
        iEvento = cmbEvento.getSelectedIndex();
        if (iEvento != -1) {
            Evento e = new Evento();
            e = empresa.getM_registoEventos().getEvento((String) cmbEvento.getSelectedItem());

            if (!(txtTitulo.getText().isEmpty() || txtResumo.getText().isEmpty())) {

                while (JOptionPane.showConfirmDialog(this, "Adicionar autor?", "Adicionar autores",
                        JOptionPane.YES_NO_OPTION) == 0) {

                    String nomeAutor = JOptionPane.showInputDialog(this, "Nome do autor:",
                            "Inserir autores", JOptionPane.OK_CANCEL_OPTION);
                    Utilizador autor = submeterArtigoController.obterAutor(nomeAutor);
                    String afiliacao = "";
                    if (autor != null) {
                        afiliacao = JOptionPane.showInputDialog(this, "Afiliação:",
                                "Inserir afiliação", JOptionPane.OK_CANCEL_OPTION);
                        submeterArtigoController.iniciarSubmissao();
                        submeterArtigoController.selectEvento(empresa.getM_registoEventos().
                                getEvento((String) cmbEvento.getSelectedItem()));

                        submeterArtigoController.addAutor(submeterArtigoController.
                                novoAutor(autor.getM_strNome(), afiliacao));

                    } else {
                        JOptionPane.showMessageDialog(this, "O autor introduzido não faz parte da lista de utilizadores!",
                                "Submeter artigo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
                jPan1.setVisible(false);
                jPanel2.setVisible(true);
                for (Autor autorCorrespondente : submeterArtigoController.getPossiveisAutoresCorrespondentes()) {
                    cmbAutorCorr.addItem(autorCorrespondente.getM_strNome());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tem que inserir um titulo e resumo do artigo!",
                        "Dados inválidos!", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "Tem que seleccionar um evento primeiro");
        }
    }//GEN-LAST:event_btnSubmeterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmeterArtigoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubmeterArtigoUI dialog = new SubmeterArtigoUI(new javax.swing.JFrame(), true, empresa);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmeter;
    private javax.swing.JComboBox cmbAutorCorr;
    private javax.swing.JComboBox cmbEvento;
    private javax.swing.JPanel jPan1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutorCorrespondente;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextArea txtResumo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
